title:            Ditro
description:      Coding is a lifestyle.
url:              DeathKing.github.io 
signoff:          DeathKing
disqus_shortname: deathking

safe:             false

links:
  - name:         About
    url:          /about
  - name:         Article
    url:          /
  - name:         Quiz
    url:          /quiz
  - name:         Gallery
    url:          /gallery
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:     ["tables"]
