title:            刘慧斌
description:      Coding is a lifestyle.
url:              liuhuibin.github.io
signoff:          DeathKing
disqus_shortname: deathking

safe:             false

links:
  - name:         About
    url:          /about
  - name:         Article
    url:          /
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:     ["tables"]
